namespace AiCV.Infrastructure.Services;

public class GoogleGeminiService(
    HttpClient httpClient,
    string apiKey,
    string modelId,
    IStringLocalizer<AicvResources> localizer,
    bool isOAuthToken = false
) : AiServiceBase(localizer)
{
    private readonly HttpClient _httpClient = httpClient;
    private readonly string _apiKey = apiKey;
    private readonly string _modelId = modelId;
    private readonly bool _isOAuthToken = isOAuthToken;

    protected override AIProvider Provider => AIProvider.GoogleGemini;

    /// <summary>
    /// Builds the Gemini API URL. Uses ?key= for API keys, or Authorization: Bearer for OAuth tokens.
    /// </summary>
    private string GetApiUrl(string action) =>
        $"https://generativelanguage.googleapis.com/v1beta/models/{_modelId}:{action}" +
        (_isOAuthToken ? string.Empty : $"?key={_apiKey}");

    private HttpRequestMessage BuildRequest(HttpMethod method, string action, object body)
    {
        var request = new HttpRequestMessage(method, GetApiUrl(action))
        {
            Content = JsonContent.Create(body),
        };
        if (_isOAuthToken)
            request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", _apiKey);
        return request;
    }

    protected override async Task<HttpResponseMessage> SendProbeRequestAsync()
    {
        var requestBody = new
        {
            contents = new[] { new { parts = new[] { new { text = "Test" } } } },
            generationConfig = new { maxOutputTokens = 1 },
        };

        var request = BuildRequest(HttpMethod.Post, "generateContent", requestBody);
        return await _httpClient.SendAsync(request);
    }

    public override async Task<string> GenerateCoverLetterAsync(
        CandidateProfile profile,
        JobPosting job,
        string? customPrompt = null
    )
    {
        var systemPrompt = AISystemPrompts.CoverLetterSystemPrompt;
        if (!string.IsNullOrWhiteSpace(customPrompt))
            systemPrompt += $"\n\nAdditional Instructions: {customPrompt}";
        var prompt = $"{systemPrompt}\n\n{BuildPrompt(profile, job)}";
        var requestBody = new
        {
            contents = new[] { new { parts = new[] { new { text = prompt } } } },
        };

        var response = await _httpClient.SendAsync(BuildRequest(HttpMethod.Post, "generateContent", requestBody));

        if (!response.IsSuccessStatusCode)
        {
            var error = await response.Content.ReadAsStringAsync();
            throw new Exception(
                AIErrorMapper.MapError(
                    AIProvider.GoogleGemini,
                    error,
                    response.StatusCode,
                    _localizer
                )
            );
        }

        var responseJson = await response.Content.ReadAsStringAsync();
        var geminiResponse = JsonSerializer.Deserialize<GeminiResponse>(responseJson);

        return geminiResponse?.Candidates?[0]?.Content?.Parts?[0]?.Text
            ?? "Error: No content generated.";
    }

    public override async Task<TailoredResumeResult> GenerateTailoredResumeAsync(
        CandidateProfile profile,
        JobPosting job,
        string? customPrompt = null
    )
    {
        var systemPrompt = AISystemPrompts.ResumeTailoringSystemPrompt;
        if (!string.IsNullOrWhiteSpace(customPrompt))
            systemPrompt += $"\n\nAdditional Instructions: {customPrompt}";
        var prompt = $"{systemPrompt}\n\n{BuildPrompt(profile, job, isResume: true)}";
        var requestBody = new
        {
            contents = new[] { new { parts = new[] { new { text = prompt } } } },
        };

        var response = await _httpClient.SendAsync(BuildRequest(HttpMethod.Post, "generateContent", requestBody));

        if (!response.IsSuccessStatusCode)
        {
            var error = await response.Content.ReadAsStringAsync();
            throw new Exception(
                AIErrorMapper.MapError(
                    AIProvider.GoogleGemini,
                    error,
                    response.StatusCode,
                    _localizer
                )
            );
        }

        var responseJson = await response.Content.ReadAsStringAsync();
        var geminiResponse = JsonSerializer.Deserialize<GeminiResponse>(responseJson);
        var textResponse = geminiResponse?.Candidates?[0]?.Content?.Parts?[0]?.Text;

        if (string.IsNullOrEmpty(textResponse))
        {
            throw new Exception("No content generated by Gemini.");
        }

        // Clean up JSON markdown code blocks if present
        textResponse = textResponse.Replace("```json", "").Replace("```", "").Trim();

        return AIResponseParser.ParseTailoredResume(textResponse, profile);
    }

    public override async Task<string> GenerateApplicationEmailAsync(
        CandidateProfile profile,
        JobPosting job,
        string coverLetter,
        string? customPrompt = null
    )
    {
        var systemPrompt = AISystemPrompts.ApplicationEmailSystemPrompt;
        if (!string.IsNullOrWhiteSpace(customPrompt))
            systemPrompt += $"\n\nAdditional Instructions: {customPrompt}";

        var userPrompt = BuildEmailPrompt(profile, job, coverLetter);

        var prompt = $"{systemPrompt}\n\n{userPrompt}";

        var requestBody = new
        {
            contents = new[] { new { parts = new[] { new { text = prompt } } } },
        };

        var response = await _httpClient.SendAsync(BuildRequest(HttpMethod.Post, "generateContent", requestBody));

        if (!response.IsSuccessStatusCode)
        {
            var error = await response.Content.ReadAsStringAsync();
            throw new Exception(
                AIErrorMapper.MapError(
                    AIProvider.GoogleGemini,
                    error,
                    response.StatusCode,
                    _localizer
                )
            );
        }

        var responseJson = await response.Content.ReadAsStringAsync();
        var geminiResponse = JsonSerializer.Deserialize<GeminiResponse>(responseJson);

        return geminiResponse?.Candidates?[0]?.Content?.Parts?[0]?.Text
            ?? "Error: No content generated.";
    }

    // Response DTOs
    private class GeminiResponse
    {
        [JsonPropertyName("candidates")]
        public GeminiCandidate[]? Candidates { get; set; }
    }

    private class GeminiCandidate
    {
        [JsonPropertyName("content")]
        public GeminiContent? Content { get; set; }
    }

    private class GeminiContent
    {
        [JsonPropertyName("parts")]
        public GeminiPart[]? Parts { get; set; }
    }

    private class GeminiPart
    {
        [JsonPropertyName("text")]
        public string? Text { get; set; }
    }
}
